.PHONY: clean, get, generate, regenerate, format, lint, fix, icon, splash, intl, sign, build-apk, report

clean: ## Cleans the environment
	@echo "╠ Cleaning the project..."
	@fvm flutter clean

get: ## Get project dependencies
	@echo "╠ Get dependencies"
	@fvm flutter pub get

generate: ## Generates autogenerated code
	@echo "╠ Generating code"
	@fvm flutter pub run build_runner build

regenerate: ## Regenerates autogenerated code
	@echo "╠ Re-generating code"
	@fvm flutter pub run build_runner build --delete-conflicting-outputs

format: ## Formats the code
	@echo "╠ Formatting the code"
	dart format .

lint: ## Lints the code
	@echo "╠ Verifying code..."
	@fvm flutter analyze . || (echo "Error in project"; exit 1)

fix: ## Fix the code
	@echo "╠ Fixing the code"
	dart fix --apply .

icon: ## Generates launcher icon
	@echo "╠ Making launcher icon"
	@fvm flutter pub run flutter_launcher_icons -f flutter_launcher_icons*

splash: ## Generates native splash
	@echo "╠ Making native splash"
	@fvm flutter pub run flutter_native_splash:create

intl:
	flutter pub run intl_utils:generate

sign: ## Sign apk
	@echo "╠ Signing apk..."
	keytool -genkey -v -keystore key.jks -storetype JKS -keyalg RSA -keysize 2048 -validity 10000 -alias key

build-apk: ## Build mobile application
	@echo "╠ Building mobile application"
	@fvm flutter build apk --release --flavor $(flavour) -t lib/shared/presentation/flavour/flavour_1/main.dev.dart --shrink --obfuscate --split-debug-info=./obfuscatation/debug


report: ## Generate test report
	@echo "╠ Installing cucumber-html-reporter..."
	npm install cucumber-html-reporter --save-dev

	@echo "╠ Generating reporter..."
	node test_driver/index.js

